modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId="formulatooltips"
version="${file.jarVersion}"
displayName="Fomula Tooltips"
authors="TheEmosewaPixel"
description="A mod adding tooltips with the chemical formulas for items made from materials added by Pixel Lib"
[[dependencies.formulatooltips]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.formulatooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.formulatooltips]]
    modId="pixellib"
    mandatory=true
    versionRange="[1.0.6,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.formulatooltips]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.6,)"
    ordering="AFTER"
    side="BOTH"