modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId="formulatooltips"
version="${file.jarVersion}"
displayName="Fomula Tooltips"
authors="TheEmosewaPixel"
description="A mod adding tooltips with the chemical formulas for items made from materials added by Pixel Lib"
[[dependencies.formulatooltips]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.formulatooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.formulatooltips]]
    modId="pixellib"
    mandatory=true
    versionRange="[1.0.7,]"
    ordering="AFTER"
    side="BOTH"